import {
  defineConfig,
  presetUno,
  presetIcons,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss';

export default defineConfig({
  presets: [
    presetUno(),
    presetIcons({
      scale: 1.2,
      cdn: 'https://esm.sh/',
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
    presetWebFonts({
      fonts: {
        sans: 'Inter:400,500,600,700,800',
        mono: 'JetBrains Mono:400,500,600',
      },
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  theme: {
    colors: {
      primary: {
        50: '#eef2ff',
        100: '#e0e7ff',
        200: '#c7d2fe',
        300: '#a5b4fc',
        400: '#818cf8',
        500: '#6366f1',
        600: '#4f46e5',
        700: '#4338ca',
        800: '#3730a3',
        900: '#312e81',
      },
      dark: {
        50: '#f8fafc',
        100: '#1e293b',
        200: '#1a1f2e',
        300: '#151922',
        400: '#10131a',
        500: '#0c0e14',
        600: '#080a0f',
        700: '#050608',
        800: '#030405',
        900: '#000000',
      },
      accent: {
        green: '#10b981',
        blue: '#3b82f6',
        purple: '#8b5cf6',
        pink: '#ec4899',
        orange: '#f97316',
        cyan: '#06b6d4',
      },
    },
    animation: {
      keyframes: {
        'float': '{0%, 100% { transform: translateY(0px) } 50% { transform: translateY(-20px) }}',
        'glow': '{0%, 100% { opacity: 1 } 50% { opacity: 0.5 }}',
        'slide-up': '{from { opacity: 0; transform: translateY(30px) } to { opacity: 1; transform: translateY(0) }}',
        'fade-in': '{from { opacity: 0 } to { opacity: 1 }}',
        'gradient': '{0% { background-position: 0% 50% } 50% { background-position: 100% 50% } 100% { background-position: 0% 50% }}',
      },
      durations: {
        'float': '6s',
        'glow': '2s',
        'slide-up': '0.6s',
        'fade-in': '0.4s',
        'gradient': '3s',
      },
      timingFns: {
        'float': 'ease-in-out',
        'glow': 'ease-in-out',
        'slide-up': 'ease-out',
        'fade-in': 'ease-out',
        'gradient': 'ease',
      },
      counts: {
        'float': 'infinite',
        'glow': 'infinite',
        'gradient': 'infinite',
      },
    },
  },
  shortcuts: [
    ['btn', 'px-6 py-3 rounded-xl font-semibold transition-all duration-300 cursor-pointer'],
    ['btn-primary', 'btn bg-gradient-to-r from-primary-500 to-primary-600 text-white hover:from-primary-600 hover:to-primary-700 hover:shadow-lg hover:shadow-primary-500/25 hover:-translate-y-0.5'],
    ['btn-secondary', 'btn bg-dark-200 text-white border border-dark-100 hover:bg-dark-100 hover:border-primary-500/50'],
    ['glass', 'backdrop-blur-xl bg-dark-300/60 border border-white/5'],
    ['glass-hover', 'glass hover:bg-dark-200/80 hover:border-primary-500/30 transition-all duration-300'],
    ['gradient-text', 'bg-gradient-to-r from-primary-400 via-accent-purple to-accent-pink bg-clip-text text-transparent'],
    ['section-padding', 'py-20 md:py-32 px-4 md:px-8'],
    ['container-custom', 'max-w-7xl mx-auto'],
    ['card', 'rounded-2xl p-6 glass-hover'],
    ['heading-xl', 'text-4xl md:text-6xl lg:text-7xl font-bold leading-tight'],
    ['heading-lg', 'text-3xl md:text-4xl font-bold'],
    ['heading-md', 'text-xl md:text-2xl font-semibold'],
    ['text-muted', 'text-gray-400'],
    ['link-hover', 'hover:text-primary-400 transition-colors duration-200'],
  ],
  safelist: [
    'i-carbon-checkmark-filled',
    'i-carbon-radio-button',
    'i-carbon-logo-github',
    'i-carbon-document',
    'i-carbon-code',
    'i-carbon-tree-view',
    'i-carbon-analytics',
    'i-carbon-rocket',
    'i-carbon-flash',
    'i-carbon-paint-brush',
    'i-carbon-settings-adjust',
    'i-carbon-sync',
    'i-carbon-terminal',
    'i-carbon-folder',
    'i-carbon-chevron-right',
    'i-carbon-arrow-right',
    'i-carbon-star-filled',
    'i-carbon-chart-line',
    'i-carbon-badge',
  ],
});
